### ISSUE TITLE
IP location & display

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#103]
Not sure if this is implemented yet.  Results are suppose to display based on IP address & location.

**Comment by denisha-addweb** [comment]
IP location development is complete now authenticated user,administrator set "Oregon" state,and anonymous user set own ip location and that type of data is not available so that no data will display if you want to check then add ads for "Oregon" state and check on authenticated user,administrator user.

**Comment by saurabhd** [comment]
Can you please explain the purpose of adding "Question" label here?

**Comment by atlantaluck** [comment]
I thought I had a question that's why I labeled it as a question.  Please explain to me more on this.  So, the backend and the whole site is set to "Oregon" only for the purpose of testing?

**Comment by saurabhd** [comment]
Yes, this is for testing purpose as we discussed over Skype.
